version: '3.8'
services:
  chat-rocketchat:
    image: rocketchat/rocket.chat
    restart: always
    user: rocketchat
    environment:
      - ROOT_URL=http://localhost
      - MONGO_URL=mongodb://mongo:27017/rocketchat
      - MONGO_OPLOG_URL=mongodb://mongo:27017/rocketchat
  mongo:
    image: mongo:4.0
    restart: always
    volumes:
      - ./data/db:/data/db
      - ./data/dump:/dump
    command: mongod --smallfiles --oplogSize 128 --replSet rs0
  mongo-init:
    image: mongo:4.0
    command: 'mongo mongo/rocketchat --eval "rs.initiate({ _id: ''rs0'', members: [ { _id: 0, host: ''localhost:27017'' } ]})"'
